messaging/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from messaging.views import UserApiView, UserDetail, MessageApiView, MessageDetail, SearchUser, AdminApiView, \
    AdminDetail, LikeApiView, LikeDetail, SeenApiView, ArchiveApiView, ChannelApiView, ChannelDetail, GroupDetail, \
    GroupApiView, Log, Sign, UserEdit, AccountChats, AccountGroups, AccountChannels, AccountPv, Unlike, GroupChats, \
    Groupmembers, ChannelChats, ChannelMembers, AddChannelMember, JoinChannel, Invielink, LeaveChannel, ChannelAdress, \
    AddGroupMember, LeaveGroup, JoinGroup, GInvielink, GroupEdit, ChannelAdmins, GroupAdmins, LoginView, LogOut, \
    ChannelSeen, GroupSeen, MessageSeen, AccountArchived, UnArchive, home, send_push

app_name = 'messaging'
urlpatterns = [
    path('user', UserApiView.as_view(), name='UserApi'),
    path('user/<int:pk>/', UserDetail.as_view(), name='UserDetail'),
    path('user/edit/<int:pk>/', UserEdit.as_view(), name='UserEdit'),
    path('search/<str:search>/', SearchUser.as_view(), name='SearchUserApi'),
    path('message', MessageApiView.as_view(), name='messageApi'),
    path('message/<int:pk>/', MessageDetail.as_view(), name='messageDetail'),
    path('admin', AdminApiView.as_view(), name='adminApi'),
    path('admin/<int:pk>/', AdminDetail.as_view(), name='adminDetail'),
    path('like', LikeApiView.as_view(), name='likeApi'),
    path('like/<int:pk>/', LikeDetail.as_view(), name='likeDetail'),
    path('seen', SeenApiView.as_view(), name='seenApi'),
    path('archive', ArchiveApiView.as_view(), name='ArchiveApi'),
    path('archive/<int:pk>/', AdminDetail.as_view(), name='AdminDetail'),
    path('channel', ChannelApiView.as_view(), name='channelApi'),
    path('channel/<int:pk>/', ChannelDetail.as_view(), name='channelDetail'),
    path('channel/admins/<int:pk>/', ChannelAdmins.as_view(), name='ChannelAdmins'),
    path('group/admins/<int:pk>/', GroupAdmins.as_view(), name='GroupAdmins'),
    path('group', GroupApiView.as_view(), name='GroupApi'),
    path('group/<int:pk>/', GroupDetail.as_view(), name='GroupDetail'),
    path('groupE/<int:pk>/', GroupEdit.as_view(), name='GroupEdit'),
    path('log', LoginView, name='login'),
    path('sign', Sign.as_view(), name='sign'),
    path('logout', LogOut, name='LogOut'),
    path('account/chats/<int:pk>/', AccountChats.as_view(), name='AccountChats'),
    path('account/archived/<int:pk>/', AccountArchived.as_view(), name='AccountArchived'),
    path('account/groups/<int:pk>/', AccountGroups.as_view(), name='AccountGroups'),
    path('account/channels/<int:pk>/', AccountChannels.as_view(), name='AccountChannels'),
    path('account/pv/<int:pk1>/<int:pk2>/', AccountPv.as_view(), name='AccountPv'),
    path('unlike/<int:pk1>/<int:pk2>/', Unlike.as_view(), name='unlike'),
    path('seen/channel/<int:pk1>/<int:pk2>/', ChannelSeen.as_view(), name='ChannelSeen'),
    path('seen/group/<int:pk1>/<int:pk2>/', GroupSeen.as_view(), name='GroupSeen'),
    path('group/chats/<int:pk1>', GroupChats.as_view(), name='GroupChats'),
    path('group/members/<int:pk1>', Groupmembers.as_view(), name='Groupmembers'),
    path('channel/chats/<int:pk1>', ChannelChats.as_view(), name='ChannelChats'),
    path('group/chats/<int:pk1>', GroupSeen.as_view(), name='GroupSeen'),
    path('message/seen/<int:pk1>', MessageSeen.as_view(), name='MessageSeen'),
    path('channel/members/<int:pk1>', ChannelMembers.as_view(), name='ChannelMembers'),
    path('channel/join/<int:pk1>/<int:pk2>/', JoinChannel.as_view(), name='JoinChannel'),
    path('group/join/<int:pk1>/<int:pk2>/', JoinGroup.as_view(), name='JoinGroup'),
    path('unarchive/<int:pk1>/<int:pk2>/', UnArchive.as_view(), name='UnArchive'),
    path('channel/leave/<int:pk1>/<int:pk2>/', LeaveChannel.as_view(), name='LeaveChannel'),
    path('channel/add/<int:pk>', AddChannelMember.as_view(), name='AddChannelMember'),
    path('group/add/<int:pk>', AddGroupMember.as_view(), name='AddGroupMember'),
    path('group/leave/<int:pk1>/<int:pk2>/', LeaveGroup.as_view(), name='LeaveGroup'),
    path('channel/link/<str:token>', Invielink.as_view(), name='Invielink'),
    path('group/link/<str:token>', GInvielink.as_view(), name='GInvielink'),
    path('c/<str:link>', ChannelAdress.as_view(), name='ChannelAdress'),
    path('h', home, name='home'),
    path('send_push', send_push),
    path('webpush/', include('webpush.urls')),
    path('sw.js', TemplateView.as_view(template_name='sw.js', content_type='application/x-javascript')),

]

sendix/urls.py
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('messaging.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

messaging/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from messaging.models import  User, Message, Admin, Like, Archived, Channel, Group, Seen
from messaging.serializers import UserSerializer, MessageSerializer, AdminSerializer, LikeSerializer, SeenSerializer, \
    ArchiveSerializer, ChannelSerializer, GroupSerializer, UserEditSerializer, GroupEditSerializer
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView


class UserApiView(APIView):
    def get(self, request):
        query = User.objects.all()
        serializer = UserSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserEdit(APIView):
    def put(self, request, pk):
        query = User.objects.filter(pk=pk).first()
        serializer = UserEditSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserDetail(APIView):
    def get_object(self, pk):
        try:
            return User.objects.filter(pk=pk)
        except User.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        query = self.get_object(pk)
        serializer = UserSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request, pk):
        query = User.objects.filter(pk=pk).first()
        serializer = UserSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        query = self.get_object(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class SearchUser(APIView):
    def get_object(self, search):
        return User.objects.filter(Q(first_name__contains=search) | Q(last_name__contains=search))

    def get(self, request, search):
        query = self.get_object(search)
        serializers = UserSerializer(query, many=True, context={'request': request})
        return Response(serializers.data, status=status.HTTP_200_OK)


class MessageApiView(APIView):
    def get(self, request):
        query = Message.objects.all()
        serializer = MessageSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = MessageSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class MessageDetail(APIView):
    def get_object(self, pk):
        try:
            return Message.objects.filter(pk=pk)
        except Message.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        query = self.get_object(pk)
        serializer = MessageSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request, pk):
        query = Message.objects.filter(pk=pk).first()
        serializer = MessageSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        query = self.get_object(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class AdminApiView(APIView):
    def post(self, request):
        serializer = AdminSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class AdminDetail(APIView):
    def get_object(self, pk):
        try:
            return Admin.objects.filter(pk=pk)
        except Admin.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        query = self.get_object(pk)
        serializer = AdminSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request, pk):
        query = Admin.objects.filter(pk=pk).first()
        serializer = AdminSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        query = self.get_object(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class LikeApiView(APIView):
    def post(self, request):
        serializer = LikeSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LikeDetail(APIView):
    def get_object(self, pk):
        try:
            return Like.objects.filter(pk=pk)
        except Like.DoesNotExist:
            raise Http404

    def put(self, request, pk):
        query = Like.objects.filter(pk=pk).first()
        serializer = LikeSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        query = self.get_object(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class Unlike(APIView):
    def get(self, request, pk1, pk2):
        account = User.objects.get(pk=pk1)
        message = Message.objects.get(pk=pk2)
        like = Like.objects.get(user=account, message=message)
        like.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)




class SeenApiView(APIView):
    def post(self, request):
        serializer = SeenSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ArchiveApiView(APIView):
    def post(self, request):
        serializer = ArchiveSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ArchiveDetail(APIView):
    def get_object(self, pk):
        try:
            return Archived.objects.filter(pk=pk)
        except Archived.DoesNotExist:
            raise Http404

    def delete(self, request, pk):
        query = self.get_object(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ChannelApiView(APIView):
    def get(self, request):
        query = Channel.objects.all()
        serializer = ChannelSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = ChannelSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ChannelDetail(APIView):
    def get_object(self, pk):
        try:
            return Channel.objects.filter(pk=pk)
        except Channel.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        query = self.get_object(pk)
        serializer = ChannelSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request, pk):
        query = Channel.objects.filter(pk=pk).first()
        serializer = ChannelSerializer(query, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        query = Channel.objects.filter(pk=pk).first()
        admins = Admin.objects.filter(channel=query)
        admins.delete()
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class GroupApiView(APIView):
    def get(self, request):
        query = Group.objects.all()
        serializer = GroupSerializer(query, many=True, context={'request': request})
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = GroupSerializer(data=request.data)

messaging/templates/messaging/base.html
{% load static %}
<DOCTYPE html>
    <html lang="eng" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                Login
            {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static "messaging/log.css" %}">
    </head>
    <body>
    <div class="box">
        <form class="sign" action={% url 'messaging:login' %} method="post">
            <h1>MessagingApp</h1>
            {% csrf_token %}
            {{ form }}
        <input  type="submit" value="login" style="background: lightskyblue; border-radius: 50px; margin-left: 250px; margin-top: 20px">
        </form>
    </div>

    </body>
    </html>
    <style scope>
        span.helptext{
            color: snow;
        }
        form.sign {
            margin-top: 200px;
            align-items: center;
            border-radius: 120px 150px 90px 190px;
            background-color: #33322f;
            width : 350px ;
            height : 250px;
            padding: 50px;
            position  :center ;
            margin-top: 100px;
            margin-left: 150px;
        }
        h1{
            margin-bottom: 20px;
            color: snow;
        }

        input{
            color: #1b1b1b;
            background-color: whitesmoke;
            padding: 10px;
            margin: 5px;

        }
        label{
            color: lightskyblue;
            padding: 5px;
            margin: 5px;
        }
    </style>

messaging/templates/messaging/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="vapid-key" content="{{ vapid_key }}">
    {% if user.id %}
        <meta name="user_id" content="{{ user.id }}">
    {% endif %}
    <title>Web Push</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static "messaging/style.css" %}">

</head>

<body>

<div>
    <form id="send-push__form">
        <h3 class="header">Send a push notification</h3>
        <p class="error"></p>
        <input type="text" name="head" placeholder="Header: Your favorite airline ?">
        <textarea name="body" id="" cols="30" rows="10" placeholder="Body: Your flight has been cancelled ???"></textarea>
        <button>Send Me</button>
    </form>
</div>
   <script src="{% static 'messaging/js/registerSw.js' %}"></script>
   <script src="{% static 'messaging/js/site.js' %}"></script>

</body>
</html>

messaging/templates/messaging/signup.html
{% load static %}
<DOCTYPE html>
    <html lang="eng" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
                Sign UP
            {% endblock %}
        </title>
        <link rel="stylesheet" href="{% static "share/all.css" %}">
    </head>
    <body>
    <form class="sign" action={% url 'share:signup' %} method="post">
        {% csrf_token %}
        <h1>Sign Up Dongeto</h1>
        {{ form }}
        <input type="submit" value="login" style="background: #67b168; border-radius: 5px">

    </form>
    </html>
    <style scope>
        span.helptext{
            color: snow;
        }
        form.sign {
            margin-top: 200px;
            align-items: center;
            border-radius: 20px;
            background-color: seagreen;
            width : 250px ;
            height : auto;
            padding: 50px;
            position  :center ;
            margin: auto;
        }
        h1{
            margin-bottom: 20px;
            color: snow;
        }

        input{
            color: #1b1b1b;
            background-color: whitesmoke;
            padding: 10px;
            margin: 5px;

        }
        label{
            color: mediumspringgreen;
            padding: 5px;
            margin: 5px;
        }
        button{
            margin: 10px;
            padding: 10px;
            background-color: #5cb85c;
            border-radius: 3px;
        }
    </style>